export const INGREDIENT_POPULATE = 'INGREDIENT_POPULATE';
export const INGREDIENT_POPULATE_START = 'INGREDIENT_POPULATE_START';
export const INGREDIENT_POPULATE_SUCCESS = 'INGREDIENT_POPULATE_SUCCESS';
export const INGREDIENT_POPULATE_FAIL = 'INGREDIENT_POPULATE_FAIL';

export const INGREDIENT_MOVE = 'INGREDIENT_MOVE';
export const INGREDIENT_MOVE_START = 'INGREDIENT_MOVE_START';
export const INGREDIENT_MOVE_SUCCESS = 'INGREDIENT_MOVE_SUCCESS';
export const INGREDIENT_MOVE_FAIL = 'INGREDIENT_MOVE_FAIL';

export const INGREDIENT_ADD = 'INGREDIENT_ADD';
export const INGREDIENT_ADD_START = 'INGREDIENT_ADD_START';
export const INGREDIENT_ADD_SUCCESS = 'INGREDIENT_ADD_SUCCESS';
export const INGREDIENT_ADD_FAIL = 'INGREDIENT_ADD_FAIL';



